#eureka config
spring.cloud.discovery.enabled=false
eureka.client.service-url.defaultZone=http://192.168.6.111:8761/eureka
eureka.client.register-with-eureka=false
eureka.instance.prefer-ip-address=true

