#eureka config
spring.cloud.discovery.enabled=false
eureka.client.service-url.defaultZone=http://netflix:eureka@localhost:8761/eureka
eureka.client.register-with-eureka=false
eureka.instance.prefer-ip-address=true

